### ISSUE TITLE
Failed build project

### ISSUE THREAD

**Issue by SuperErnD** [lovebrew/lovebrew-webserver#1]
While building the example project (https://transfer.sh/0MEzFhxGBo/proj.zip)
returns this log
05:41 [CRIT] An exception occurred: Traceback (most recent call last):
  File "/home/turtlep/lovebrew-webserver/lovebrew/process.py", line 29, in build_target
    error = console.pre_build(build_dir, data[0], data[1]).build(build_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turtlep/lovebrew-webserver/lovebrew/consoles/ctr.py", line 59, in build
    "icon": self.icon_file(),
            ^^^^^^^^^^^^^^^^
  File "/home/turtlep/lovebrew-webserver/lovebrew/console.py", line 65, in icon_file
    return self.path_to(f"icon.{extension}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turtlep/lovebrew-webserver/lovebrew/console.py", line 84, in path_to
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/turtlep/lovebrew-webserver/lovebrew/bin/ctr/icon.png'

But bin/ctr/icon.png is exists!

**Comment by TurtleP** [comment]
Seems I forgot to move the proper binary information on the server after moving files around. That's my bad. It should be fixed, but I'll quickly restart *just* in case.
